name: hexlet-project-lvl1

on: push

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: install poetry
        run: pip install poetry
      - name: install env
        run: make install
      - name: Run linter
        run: make lint